# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=10)),
                ('customergroup', models.CharField(max_length=5)),
            ],
        ),
    ]
