# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170623_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ardid',
            new_name='adrid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='createdate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='createuser',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modifydate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modifyuser',
        ),
    ]
