# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170623_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customergroup', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=30)),
                ('norange', models.CharField(max_length=5)),
            ],
        ),
    ]
