# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170623_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isocode', models.CharField(max_length=2)),
                ('isocode2', models.CharField(max_length=3)),
                ('carplate', models.CharField(max_length=3)),
                ('zipcheckrule', models.CharField(max_length=5)),
            ],
        ),
    ]
