# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_countries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Nation',
        ),
    ]
