# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170623_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='ziplenght',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nation',
            name='zipmandatory',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
