# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170623_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accountant',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='adrid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='client',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='compid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='startup',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vatid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='www',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='customergroup',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='norange',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='nation',
            name='carplate',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='nation',
            name='isocode',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='nation',
            name='isocode2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='nation',
            name='zipcheckrule',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='nation',
            name='ziplenght',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
