# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170623_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legalform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalform', models.CharField(max_length=2)),
                ('legaltype', models.CharField(max_length=1)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Nation')),
            ],
        ),
    ]
