# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170623_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalform',
            name='legaltype',
            field=models.CharField(choices=[('PS', 'Personal'), ('CR', 'Corporate')], max_length=1),
        ),
    ]
