# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170623_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isocode', models.CharField(max_length=3, unique=True)),
                ('datevalend', models.DateTimeField()),
            ],
        ),
    ]
