# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adrid', models.CharField(max_length=10, unique=True)),
                ('adrtype', models.CharField(choices=[('DO', 'Domicile'), ('PO', 'Postal')], max_length=1)),
                ('line1', models.CharField(blank=True, max_length=30, null=True)),
                ('line2', models.CharField(blank=True, max_length=30, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Nation', to_field='isocode')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2, unique=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Nation', to_field='isocode')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.State', to_field='state'),
        ),
    ]
