# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170623_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adrid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Address', to_field='adrid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='legalform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Legalform', to_field='legalform'),
        ),
        migrations.AlterField(
            model_name='legalform',
            name='legalform',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
