# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170623_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contid', models.CharField(max_length=10, unique=True)),
                ('contgroup', models.CharField(max_length=5)),
                ('conttype', models.CharField(choices=[('CUST', 'Cstomer'), ('ACC', 'Accountant')], max_length=5)),
                ('salut', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.')], max_length=3)),
                ('first', models.CharField(blank=True, max_length=30, null=True)),
                ('middle', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.CharField(blank=True, max_length=1, null=True)),
                ('role', models.CharField(blank=True, max_length=1, null=True)),
                ('adrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Address', to_field='adrid')),
            ],
        ),
    ]
